"""Initial migration

Revision ID: 0f225353e1db
Revises: 
Create Date: 2025-07-27 02:07:06.042685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f225353e1db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_records', sa.Column('is_judged', sa.Boolean(), nullable=True, comment='是否已经被判断过'))
    op.add_column('chat_records', sa.Column('is_used', sa.Boolean(), nullable=True, comment='是否被使用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_records', 'is_used')
    op.drop_column('chat_records', 'is_judged')
    # ### end Alembic commands ###
