vector_db:
  type: "chroma"
  collection_name: "documents"
  persist_directory: ".db/chroma_db"

embeddings:
  type: "dashscope"
  model: "text-embedding-v3"
  api_key: "${ALIYUN_API_KEY}"
  
chunk_size: 256
chunk_overlap: 16
supported_file_types: 
  - ".txt"
  - ".pdf"
  - ".docx"
  - ".md"
  - ".xlsx"
  - ".csv"

self_rag: false
feedback:
  type: "aliyun"
  api_key: "${ALIYUN_API_KEY}"
  model_name: "qwen-plus"
  temperature: 0.7 
  max_tokens: 2000
  api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"