vector_db:
  type: "milvus"
  collection_name: "documents"
  uri: "https://in03-64eca050ccbbca9.serverless.aws-eu-central-1.cloud.zilliz.com"
  token: "${MILVUS_TOKEN}"
  database: "default"

embeddings:
  type: "dashscope"
  model: "text-embedding-v3"
  api_key: "${ALIYUN_API_KEY}"
  
chunk_size: 256
chunk_overlap: 16
supported_file_types: 
  - ".txt"
  - ".pdf"
  - ".docx"
  - ".md"
  - ".xlsx"
  - ".csv"

self_rag: false
feedback:
  type: "aliyun"
  api_key: "${ALIYUN_API_KEY}"
  model_name: "qwen-plus"
  temperature: 0.7 
  max_tokens: 2000
  api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"